version: '3.8'

networks:
  net:
    name: net
    driver: bridge

services:
  infrastructer:
    container_name: infrastructer
    image: infrastructer
    build: ./start
    ports:
      - "8000:80"
    networks:
      - net
    restart: always