# Generated by Django 5.0.6 on 2024-09-16 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restuserm", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="friendships",
            name="receiver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="friend_request_received",
                to="restuserm.player",
            ),
        ),
        migrations.AlterField(
            model_name="friendships",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="friend_request_sent",
                to="restuserm.player",
            ),
        ),
        migrations.AlterField(
            model_name="playergamematch",
            name="id_player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="restuserm.player"
            ),
        ),
    ]
