arr = ["1", 2, "3", 14];
str = arr.toString();
console.log(typeof arr + ` ${arr}`);
console.log(typeof str + ` ${str}`);
lenOfArr = arr.length;
console.log(typeof lenOfArr + ` ${lenOfArr}`);
sortArr = arr.sort();
console.log(typeof sortArr + ` ${sortArr}`);
arr.push("Disorder");
console.log(typeof arr + ` ${arr}`);
arr = [];
arr["Person"] = "Zakaria";
console.log(typeof arr + ` ${arr["Person"]}`);
arr = ["1", "2", "3"];
console.log(arr);
console.log(`Erasing The First Element ${arr.shift()}`);
console.log(arr);
console.log(`The New Length Of The arr Is ${arr.unshift(1)}`);
console.log(arr);
console.log(`Erasing The Last Element ${arr.pop()}`);
console.log(arr);
arr1 = ["10", "1"];
arr2 = ["20", "2"];
arr3 = ["30", "3"];
arr4 = ["40", "4"];
console.log(arr1.concat(arr2, arr3, arr4));
fruits = ["Banana", "Orange", "Apple", "Mango"];
console.log(fruits);
fruits.copyWithin(2, 0, 1);
console.log(fruits);
fruits.splice(0, 0, "Kiwi");
console.log(fruits);

