version: '3.9'

services:
  django:
    restart: always
    image: django-docker:0.0.1
    build: .
    ports:
      - "8000:8000"
    volumes:
      - /home/zbex/Desktop/django-tutor:/usr/src/app
    # environment:
    #   - PYTHONDONTWRITEBYTECODE=1
    #   - PYTHONUNBUFFERED=1