version: "3.8"

name: ft_transcendence

services:
  postgres_db:
    container_name: postgress_db
    build:
      context: ./backend/postgresql
      dockerfile: Dockerfile
      args:
        POSTGRS_PASSWORD: ${POSTGRS_PASSWORD}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_DB: ${POSTGRES_DB}
    image: ft_postgres:1
    env_file:
      - .env
    ports:
      - "5050:5432"
    volumes:
      - postgres_db:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_db:
    driver: local
    name: postgres_db
    driver_opts:
      type: none
      device: /home/belkarto/data/postgres_db
      o: bind
