name: ft_transcendence

services:
  server:
    networks:
      - Net
    ports:
      - "8000:80"
    volumes:
      - ./frontend:/var/www/transcendence
    build: frontend/server/
    container_name: server
    image: server:v1

networks:
  Net:
    name: Net

  # postgres_db:
  #   container_name: postgres_db
  #   build:
  #     context: ./backend/postgresql
  #     dockerfile: Dockerfile
  #     args:
  #       POSTGRS_PASSWORD: ${POSTGRS_PASSWORD}
  #       POSTGRES_USER: ${POSTGRES_USER}
  #       POSTGRES_DB: ${POSTGRES_DB}
  #   image: postgres_db:1
  #   env_file:
  #     - .env
  #   networks:
  #     - Net
  #   # volumes:
  #   #   - postgres_db:/var/lib/postgresql/data
  #   restart: always


  # auth:
  #   container_name: auth
  #   build:
  #     context: ./backend/Authentication
  #     dockerfile: Dockerfile
  #   command: sh -c "python3 manage.py makemigrations --noinput  && python3 manage.py migrate --noinput && python3 manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
  #   image: auth:1337
  #   env_file:
  #     - .env
  #   networks:
  #     - Net
  #   depends_on:
  #     - postgres_db
  #   restart: always

  # chat:
  #   container_name: chat
  #   build:
  #     context: ./backend/chat
  #     dockerfile: Dockerfile
  #   command: sh -c "python3 manage.py makemigrations --noinput  && python3 manage.py migrate --noinput && python3 manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
  #   image: chat:1337
  #   env_file:
  #     - .env
  #   networks:
  #     - Net
  #   depends_on:
  #     - postgres_db
  #   restart: always

# volumes:
#   postgres_db:
#     driver: local
#     name: postgres_db
#     driver_opts:
#       type: none
#       device: /home/belkarto/data/postgres_db
#       o: bind
#   www:
#     name: front_end
#     driver: local
#     driver_opts:
#       type: none
#       device: /home/belkarto/data/www
#       o: bind
