version: "3.8"

name: ft_transcendence

networks:
  myNetwork:
    name: ft_transcendence
  # postgres_db:
  #   container_name: postgress_db
  #   build:
  #     context: ./backend/postgresql
  #     dockerfile: Dockerfile
  #     args:
  #       POSTGRS_PASSWORD: ${POSTGRS_PASSWORD}
  #       POSTGRES_USER: ${POSTGRES_USER}
  #       POSTGRES_DB: ${POSTGRES_DB}
  #   image: ft_postgres:1
  #   env_file:
  #     - .env
  #   ports:
  #     - "5050:5432"
  #   volumes:
  #     - postgres_db:/var/lib/postgresql/data
  #   restart: always
services:
  myServer:
    container_name: myServer
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: my_server:1337
    ports:
      - "443:443"
    volumes:
      - www:/var/www
    networks:
      - myNetwork
    restart: always

volumes:
  postgres_db:
    driver: local
    name: postgres_db
    driver_opts:
      type: none
      device: /home/belkarto/data/postgres_db
      o: bind
  www:
    name: front_end
    driver: local
    driver_opts:
      type: none
      device: /home/belkarto/data/www
      o: bind
