# Generated by Django 5.0.6 on 2024-05-28 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoe', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tttgame',
        ),
    ]
