# Generated by Django 5.0.6 on 2024-05-28 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tictactoe', '0002_delete_tttgame'),
    ]

    operations = [
        migrations.CreateModel(
            name='tttGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=100)),
                ('player1', models.CharField(max_length=100)),
                ('player2', models.CharField(max_length=100)),
                ('winnerRealName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tttplayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=100)),
                ('realName', models.CharField(max_length=100)),
                ('game_number', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('loses', models.IntegerField(default=0)),
            ],
        ),
    ]
