# Generated by Django 5.0.6 on 2024-05-28 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoe', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tttGame',
        ),
        migrations.DeleteModel(
            name='tttplayer',
        ),
    ]
