# Generated by Django 5.0.6 on 2024-05-28 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tictactoe', '0004_delete_tttgame_delete_tttplayer'),
    ]

    operations = [
        migrations.CreateModel(
            name='tttgame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=100)),
                ('game_creator', models.CharField(max_length=100)),
                ('game_oppenent', models.CharField(blank=True, max_length=100, null=True)),
                ('game_over', models.BooleanField(default=False)),
            ],
        ),
    ]
