# Generated by Django 5.0.6 on 2024-05-17 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('level', models.IntegerField(default=0)),
                ('gameplayed', models.IntegerField(default=0)),
                ('gamewined', models.IntegerField(default=0)),
                ('gamelosed', models.IntegerField(default=0)),
            ],
        ),
    ]
