# Generated by Django 5.0.6 on 2024-05-16 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restuserm', '0003_friendships'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlayerGameMatch',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('won', models.BooleanField(default=False)),
                ('score', models.IntegerField(default=0)),
                ('exec_path', models.CharField(max_length=255, null=True)),
                ('id_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restuserm.match')),
                ('id_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restuserm.player')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
