# Generated by Django 5.0.6 on 2024-07-01 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoe', '0002_players_board'),
    ]

    operations = [
        migrations.DeleteModel(
            name='players',
        ),
    ]
