# Generated by Django 5.0.6 on 2024-07-02 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoe', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='players',
        ),
    ]
