# Generated by Django 5.0.6 on 2024-05-15 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restuserm', '0002_auto_20240506_0350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendships',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PEN', 'PENDING'), ('ACP', 'ACCEPTED')], default='PEN', max_length=3)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_request_received', to='restuserm.player')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_request_sent', to='restuserm.player')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
