# Generated by Django 5.0.6 on 2024-05-23 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restuserm', '0004_match_playergamematch'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='game',
            field=models.CharField(choices=[('PON', 'PONG'), ('TIC', 'TICTACTOE')], default='PON', max_length=3),
        ),
        migrations.AddField(
            model_name='match',
            name='round',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='match',
            name='state',
            field=models.CharField(choices=[('PLYD', 'PLAYED'), ('UPLY', 'UNPLAYED')], default='UPLY', max_length=4),
        ),
        migrations.AlterField(
            model_name='match',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
